# Generated by Django 5.2.8 on 2025-11-20 14:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="status",
        ),
        migrations.AlterField(
            model_name="poll",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="expiry",
            field=models.DateField(
                default=datetime.date(2025, 11, 23), verbose_name="expiry"
            ),
        ),
    ]
