# Generated by Django 5.2.8 on 2025-11-20 14:14

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_poll_status_alter_poll_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="expiry",
            field=models.DateField(
                default=polls.models.expiry_default, verbose_name="expiry"
            ),
        ),
    ]
