# Generated by Django 5.2.8 on 2025-11-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_poll_expiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="description",
        ),
    ]
