# Generated by Django 5.2.8 on 2025-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_poll_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=300),
        ),
    ]
